# Generated by Django 4.2.4 on 2023-09-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_shirt_is_bestseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='title',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.TextField(max_length=20),
        ),
    ]
