# Generated by Django 4.2.4 on 2023-09-04 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_products_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='brand',
            new_name='title',
        ),
    ]
