# Generated by Django 4.2.4 on 2023-09-04 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_shirt_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='brand',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='products.brand'),
        ),
    ]
