# Generated by Django 4.2.4 on 2023-09-04 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_category_delete_shirt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
    ]
