# Generated by Django 4.2.4 on 2023-09-08 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='Products',
            new_name='products',
        ),
    ]
